---
- name: Install apache2
  hosts: webservers
  remote_user: root

  tasks:
    - name: install apache2
      yum: name=httpd state=installed
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
    - name: start service
      service: name=httpd state=started
  handlers:
    - name: restart apache2
      service: name=httpd state=started