---
# These tasks install http and the php modules.

- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql
   - git
   - libsemanage-python
   - libselinux-python
   - vim 

#- name: insert iptables rule for httpd
#  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
#              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
#  notify: restart iptables

- name: Ansible delete html directory
  file:
   path: /var/www/html
   state: directory 

- name: Ansible delete file wildcard 
  shell: rm -rf /var/www/html

#- name: server php extension
#  lineinfile: dest=/etc/php.ini state=present 
#	      linie="extension=mysqli.so"

#- name: server php extension
#  lineinfile: 
#        path: /etc/php.ini 
#        line: '{{item}}'
#        with_items:
#        -  'extension=mysqli.so' 
#        -  'extension=mysql.so'
- name: php.ini file add-on
  blockinfile: |
    dest=/etc/php.ini backup=yes
    content="extension=mysqli.so
        extension=mysql.so"


- name: http service state
  service: 
    name: httpd 
    state: started 

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0
